dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
git:
  depth: 3
cache:
  directories:
    - "$HOME/.m2"

stages:
  - run-test-one
  - trigger-downstream
jobs:
  include:
    - stage: run-test-one
      before_install:
      - git clone -b stage https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
      - ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
      install: "${PWD}/target/travis-settings/java/install.sh"
      script: "${PWD}/target/travis-settings/java/script-install.sh"
      after_success: "${PWD}/target/travis-settings/java/after_success.sh"

    - stage: trigger-downstream
      script: "sh ${PWD}/target/travis-settings/java/stage/trigger-travis.sh MartinYSpasov travis-test-two 5xNNFxSV94N1mkEm3LpsMA"
